gradebookapp/gradebookapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

gradebookapp/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('cohorts/', views.cohorts_index, name= 'index'),
    path('cohorts/create/', views.CohortCreate.as_view(), name='cohorts_create'),
    path('cohorts/<int:cohort_id>/', views.cohorts_detail, name='detail'),
    path('cohorts/<int:pk>/update/', views.CohortUpdate.as_view(), name='cohorts_update'),
    path('cohorts/<int:pk>/delete/', views.CohortDelete.as_view(), name='cohorts_delete'),
    path('cohorts/<int:cohort_id>/add_score/<int:assignment_id>/<int:student_id>/', views.add_score, name='add_score'),
    path('cohorts/<int:cohort_id>/assign_form/', views.assign_form, name='assign_form'),
    path('cohorts/<int:cohort_id>/assign_form/add_assignment/', views.add_assignment, name='add_assignment'),
    path('cohorts/<int:cohort_id>/assoc_student/<int:student_id>/', views.assoc_student, name='assoc_student'),
    path('assignments/create/', views.AssignmentCreate.as_view(), name='assignments_create'),
    path('assignments/<int:pk>/update/', views.AssignmentUpdate.as_view(), name='assignments_update'),
    path('assignments/<int:pk>/delete/', views.AssignmentDelete.as_view(), name='assignments_delete'),
    path('assignments/<int:pk>/', views.AssignmentDetail.as_view(), name='assignments_detail'),
    path('accounts/signup/', views.signup, name='signup'),
]

gradebookapp/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
class Cohort(models.Model):
    title = models.CharField(max_length=100)
    term = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Name: {self.title}, {self.term}"
    def get_absolute_url(self):
        return reverse('detail', kwargs={'cohort_id': self.id})

class Assignment(models.Model):
    cohort = models.ForeignKey(Cohort, on_delete=models.CASCADE, null=True, blank=True)
    name = models.TextField(max_length=200)
    description = models.TextField(max_length=400)
    category = models.TextField(max_length=100)
    weight = models.IntegerField()
    duedate = models.DateField("due date")
    def __str__(self):
        return f"Name: {self.name}, Due: {self.duedate}"
    def get_absolute_url(self):
        return reverse('assignments_detail', kwargs={'pk': self.id})

class Student(models.Model):
    name = models.TextField(max_length=100)
    email = models.CharField(max_length=100)
    classes = models.ManyToManyField(Cohort)
    assignments = models.ManyToManyField(Assignment, through='Grade')
    def __str__(self):
        return f"{self.name}"
    
class Grade(models.Model):
    score = models.IntegerField(blank=True, null=True)
    completed = models.BooleanField(null=True)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"student: {self.student} assignment:{self.assignment.name}"

gradebookapp/main_app/forms.py
from django.forms import ModelForm
from .models import Grade, Assignment

class GradeForm(ModelForm):
  class Meta:
    model = Grade
    fields = ['score']

class AssignmentForm(ModelForm):
  class Meta:
    model = Assignment
    fields = '__all__'

gradebookapp/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Cohort, Assignment, Student, Grade
from django.views.generic.detail import DetailView
from .forms import GradeForm, AssignmentForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def home(request):
  return render(request, 'home.html')

@login_required
def cohorts_index(request):
  cohorts = Cohort.objects.filter(user=request.user)
  return render(request, 'cohorts/index.html', {
    'cohorts': cohorts
  })

def cohorts_detail(request, cohort_id):
  cohort = Cohort.objects.get(id=cohort_id)
  students = Student.objects.filter(classes= cohort)
  student_ids = Student.objects.filter(classes= cohort).values_list('id', flat=True)
  grades = Grade.objects.all()
  grade_ids =Grade.objects.all().values_list('assignment', flat=True)
  grade_studs =Grade.objects.all().values_list('student', flat=True)
  final_grades=[]
  other_students = Student.objects.exclude(classes=cohort)
  for i in range(len(student_ids)):
    sum_grade=0
    sum_weight=0
    all_grades=Grade.objects.filter(student = student_ids[i])
    print(f'{all_grades}')
    for j in range(len(all_grades)):
      if all_grades[j].score != None:
        assignment=Assignment.objects.get(id=all_grades[j].assignment.id)
        weight = assignment.weight
        print(f"This is the weight {weight}")
        sum_weight+=weight
        score=all_grades[j].score
        print(f"This is the score {score}")
        sum_grade+=(weight*score)
    if sum_weight != 0:
      avg= sum_grade/sum_weight
      final_grades.append((avg, student_ids[i]))
  print(f"These are the tuples of our lives {final_grades}")
  grade_tuples=[]
  for i in range(len(grades)):
    grade_tuples.append((grade_ids[i], grade_studs[i]))
  grade_form = GradeForm()
  assignment_ids = Assignment.objects.filter(cohort= cohort).values_list('id', flat=True)
  other_tuples=[]
  for i in range(len(students)):
    for j in range(len(assignment_ids)):
      other_tuples.append((assignment_ids[j], student_ids[i]))
  new_tuples=[]
  for i in range(len(other_tuples)):
    if other_tuples[i] not in grade_tuples:
      new_tuples.append(other_tuples[i])
  return render(request, 'cohorts/detail.html', {
    'cohort': cohort, 'students': students, 'grades':grades, 'grade_form':grade_form, 'new_tuples':new_tuples, 'final_grades': final_grades, 'other_students': other_students
    })

def add_score(request, assignment_id, student_id, cohort_id):
  # Baby step
  form = GradeForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_grade = form.save(commit=False)
    new_grade.assignment_id = assignment_id
    new_grade.student_id = student_id
    new_grade.save()
  return redirect('detail', cohort_id=cohort_id)

def assign_form(request, cohort_id):
  cohort =  Cohort.objects.get(id=cohort_id)
  assignment_form = AssignmentForm()
  return render(request, 'assignments/form.html', {'cohort':cohort, 'assignment_form':assignment_form})

def add_assignment(request, cohort_id):
  # Baby step
  form = AssignmentForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_assignment = form.save(commit=False)
    new_assignment.cohort_id = cohort_id
    new_assignment.save()
  return redirect('detail', cohort_id=cohort_id)

class CohortCreate(LoginRequiredMixin,CreateView):
  model = Cohort
  fields = '__all__'

  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the cohort
    # Let the CreateView do its job as usual
    return super().form_valid(form)

class CohortUpdate(LoginRequiredMixin,UpdateView):
  model = Cohort
  fields = ['term']

class CohortDelete(LoginRequiredMixin,DeleteView):
  model = Cohort
  success_url = '/cohorts'

def assoc_student(request, cohort_id, student_id):
    Student.objects.get(id=student_id).classes.add(cohort_id)
    return redirect('detail', cohort_id=cohort_id)

class AssignmentCreate(LoginRequiredMixin,CreateView):
  model = Assignment
  fields = '__all__'


class AssignmentUpdate(LoginRequiredMixin,UpdateView):
  model = Assignment
  fields = '__all__'

class AssignmentDelete(LoginRequiredMixin,DeleteView):
  model = Assignment
  success_url = '/cohorts'

class AssignmentDetail(LoginRequiredMixin,DetailView):
    model = Assignment
    template_name = 'assignments/detail.html'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

gradebookapp/main_app/templates/cohorts/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{cohort.title}}</h1>
    <div class="row" style="margin-bottom: 10px;">
        <div class="col s1"><p style="font-weight: bold;">Students</p></div>
        {% for assignment in cohort.assignment_set.all %}
           <a href="{% url 'assignments_update' assignment.id %}">
            <div class="col s2" style="border: 2px solid black; display: flex; align-items: flex-start; flex-direction: column;"><p style="font-weight: bold;margin: 0;color: black;">{{ assignment.name }}</p><p style="margin: 0;">Weight: {{assignment.weight}}</p></div>
           </a>
        {% endfor %}
        <div class="col s1"><p>Final Grade</p></div>
    </div>
    {% for student in students %}
        <div class="row">
            <div class="col s1">{{student.name}}</div>
            {% for assignment in cohort.assignment_set.all %}

                <div class="col s2" style="border: 2px solid black;">
                    {%for tuple in new_tuples%}
                        {% if tuple.0 == assignment.id and tuple.1 == student.id %}
                            <form action="{% url 'add_score' cohort.id assignment.id student.id %}" method="POST">
                                {% csrf_token %}
                                <!-- Render the inputs -->
                                {{ grade_form.as_table }}
                            </form>
                        {%endif%}
                    {%endfor%}
                    {% for grade in grades %}
                        {% if grade.assignment.id == assignment.id and grade.student.id == student.id %}
                            {{grade.score}}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
            {% for tuple in final_grades %}
                {% if tuple.1 == student.id %}
                <div class="col s1"><h6>{{tuple.0}}</h6></div>
                {%endif%}
            {% endfor %}
        </div>
    {% endfor %}
    <div class="card-action">
        <button><a href="{% url 'assign_form' cohort.id %}">Add Assignment</a></button>
        <button><a href="{% url 'cohorts_update' cohort.id %}">Edit Class</a></button>
    </div>
    <div>
        <h3>Students not enrolled in this Class</h3>
        {% if other_students.count %}
        <div class="card-container">
            {% for student in other_students %}
                <div class="card student-card">
                    <div class="card-content">
                        <span class="card-title">
                            {{student.name}}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_student' cohort.id student.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="btn" value="Add to Class">
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}

gradebookapp/main_app/templates/cohorts/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Class List</h1>

{% for cohort in cohorts %}
  <div class="card">
    <a href="{% url 'detail' cohort.id %}">
        <div class="card-content">
        <span class="card-title">{{ cohort.title }}</span>
        <p>Term: {{ cohort.term }}</p>
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}